// <auto-generated />
using System;
using DemoPeliculas.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoPeliculas.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221018080032_CreacionInicial")]
    partial class CreacionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoPeliculas.Shared.Models.ListaReproduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ListaReproduccion");
                });

            modelBuilder.Entity("DemoPeliculas.Shared.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsInfantil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Tadeo vuelve a meter la pata. Esta vez, el disparatado arqueólogo destroza un sarcófago y libera la maldición de la momia que había dentro. Los amigos de Tadeo están en peligro, y solo él puede salvarlos.",
                            Duracion = "1h 29m",
                            EsInfantil = true,
                            FechaEstreno = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "tadeo.jpg",
                            NombreVideo = "tadeo.mp4",
                            Titulo = "Tadeo 3: La Maldición de la Momia"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Ha pasado un año desde que Mic Mic y Oscar regresaron de su increíble aventura. Y ahora, después de un plan diabólico de Vulture para sabotear la entrega del cachorro Grizzly a su oponente en las elecciones presidenciales, Mic Mic, Oscar, Panda adolescente y Stork emprenden otra gran aventura mientras montan en un zepelín para regresar al pequeño Grizzly a sus legítimos padres, salven las elecciones y a todo el continente de la erupción del volcán.",
                            Duracion = "1h 30m",
                            EsInfantil = true,
                            FechaEstreno = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "bebeOso.jpg",
                            NombreVideo = "bebeOso.mp4",
                            Titulo = "Operación Bebe oso"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Passepartout, un tití aficionado a los libros se embarca en una aventura salvaje para viajar alrededor del mundo en 80 días después de aceptar una apuesta.",
                            Duracion = "1h 22m",
                            EsInfantil = true,
                            FechaEstreno = new DateTime(2022, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "buscamundos.jpg",
                            NombreVideo = "buscamundos.mp4",
                            Titulo = "Los buscamundos"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "En los años 70, Gru crece siendo un gran admirador de Los Salvajes Seis, un supergrupo de villanos. Para demostrarles que puede ser malvado, diseña un plan con la esperanza de formar parte de la banda.",
                            Duracion = "1h 30m",
                            EsInfantil = true,
                            FechaEstreno = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "minions.jpg",
                            NombreVideo = "minions.mp4",
                            Titulo = "Minions: nace un villano"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "El superperro Krypto une a un grupo de divertidos y descerebrados animales para que lo ayuden a rescatar a los superhéroes de la Liga de la Justicia, que han sido secuestrados.",
                            Duracion = "1h 45m",
                            EsInfantil = true,
                            FechaEstreno = new DateTime(2022, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "supermascotas.jpg",
                            NombreVideo = "supermascotas.mp4",
                            Titulo = "DC Liga de Supermascotas"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "En un tren de alta velocidad que se dirige de Tokio a Morioka, cinco asesinos profesionales descubren que van tras el mismo objetivo.",
                            Duracion = "2h 6m",
                            EsInfantil = false,
                            FechaEstreno = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "bullet.jpg",
                            NombreVideo = "bullet.mp4",
                            Titulo = "Bullet Train"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Una mujer solitaria que vive en los inhóspitos pantanos de Carolina del Norte se convierte en la principal sospechosa del asesinato de un hombre cuyo cadáver apareció en la zona. Sin embargo, la investigación revela que nada es lo que aparenta ser.",
                            Duracion = "2h 5m",
                            EsInfantil = false,
                            FechaEstreno = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "chicaSalvaje.jpg",
                            NombreVideo = "chicaSalvaje.mp4",
                            Titulo = "La chica salvaje"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Los niños rompen accidentalmente una figurilla del Belén de colección de su padre y deben conseguir por todos los medios una igual, el problema es que es una pieza única de anticuario. Sara, la hija mayor rompe con su novio, Ocho, que intentará recuperar sus favores con la ayuda de su suegro, Javier. Precisamente el suegro de Javier, el padre de Marisa, será acogido en la casa familiar para pasar las fiestas tras su reciente separación, lo cual no dejará indiferente a la madre de Javier, Milagros.",
                            Duracion = "1h 39m",
                            EsInfantil = false,
                            FechaEstreno = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "padre.jpg",
                            NombreVideo = "padre.mp4",
                            Titulo = "Padre no hay más que uno 3"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Una pareja divorciada deja a un lado sus diferencias y viaja a Bali para evitar que su hija cometa el mismo error en el que ellos cayeron hace 25 años: casarse.",
                            Duracion = "1h 44m",
                            EsInfantil = false,
                            FechaEstreno = new DateTime(2022, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "viajeParaiso.jpg",
                            NombreVideo = "viajeParaiso.mp4",
                            Titulo = "Viaje al paraiso"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Becky y Hunter, dos amigas aficionadas al alpinismo, quedan atrapadas en la torre de telecomunicaciones de la cima de una montaña que acaban de escalar. Sin provisiones y afectadas por el vértigo, comienza la lucha por la supervivencia.",
                            Duracion = "1h 47m",
                            EsInfantil = false,
                            FechaEstreno = new DateTime(2022, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreImagen = "vertigo.jpg",
                            NombreVideo = "vertigo.mp4",
                            Titulo = "Vértigo"
                        });
                });

            modelBuilder.Entity("DemoPeliculas.Shared.Models.Puntuacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Puntuaciones");
                });

            modelBuilder.Entity("DemoPeliculas.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Adulto"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Niño"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
